/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rumbamazzo;

import javafx.stage.Stage;
import views.StartPage;
import javafx.scene.Scene;
import javafx.application.Application;

public class App extends Application {
    @Override
    public void start(Stage primaryStage) {

        Scene scene = new Scene(new StartPage().getRoot(), 300, 300);
        scene.getStylesheets().add("/style/Start.css");
        primaryStage.setScene(scene);
        primaryStage.setTitle("Rumbamazzo");
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
